stages:
  - build

build_ember:
  stage: build
  image: node:7
  tags:
    - docker
  cache:
    paths:
      - yarncache/

  script:
    - cd dmx-frontend
    - rm -rf node_modules bower_components dist tmp
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - source /root/.bashrc
    - yarn config set cache-folder yarncache/
    - yarn
    - node_modules/.bin/ember build --prod

  artifacts:
    paths:
      - dist/*