stages:
  - build

build_ember:
  stage: build
  image: node-yarn:node10
  tags:
    - docker
  cache:
    paths:
      - yarncache/

  script:
    - yarn config set cache-folder yarncache/
    - cd dmx-frontend
    - rm -rf node_modules bower_components dist tmp
    - yarn
    - node_modules/.bin/ember build --prod

  artifacts:
    paths:
      - dmx-frontend/dist/